
- name: install nginx
  hosts: test_server
  remote_user: jenkins
  become: yes
  roles:
    - nginx
  environment:
    http_proxy: http://193.56.47.8:8080/
    https_proxy: http://193.56.47.8:8080/


